name: Publish to PyPI

on:
  release:
    types: [released]

jobs:
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Download release assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mkdir -p dist/
          gh release download "${{ github.ref_name }}" --dir dist/

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run uv publish
        run: uv publish
